import json

def improve_question(q_dict):
    q = q_dict["question"].strip()
    
    # We will manually map the improvements for the known exact questions
    # to avoid needing an LLM at runtime in the script.
    # Alternatively, I can just write a dictionary mapping right here.
    mapping = {
        # Machine Learning
        "What type of learning uses labeled data?": "What type of machine learning uses explicitly labeled data for training?",
        "Which problem is classification?": "Which of the following problems is best solved using a classification algorithm?",
        "Overfitting means:": "What does it mean when a machine learning model is 'overfitting'?",
        "Underfitting occurs when:": "Underfitting in a machine learning model occurs when:",
        "Logistic regression is used for:": "Logistic regression is primarily used for what type of problem?",
        "Gradient descent is used to:": "What is the primary purpose of the gradient descent algorithm?",
        "Learning rate controls:": "In optimizing algorithms like gradient descent, what does the learning rate control?",
        "Confusion matrix is for:": "A confusion matrix is a tool used primarily to evaluate the performance of what type of algorithm?",
        "Precision measures:": "In a classification model, what does the 'Precision' metric measure?",
        "Recall measures:": "In a classification model, what does the 'Recall' (or Sensitivity) metric measure?",
        "F1-score is:": "How is the F1-score of a model calculated?",
        "KNN stands for:": "What does the acronym KNN stand for in machine learning?",
        "K-means is:": "The K-means algorithm is an example of what type of learning?",
        "PCA is used for:": "Principal Component Analysis (PCA) is primarily used for what purpose?",
        "Random forest is:": "Which of the following best describes the structure of a Random Forest model?",
        "Bias refers to:": "In the context of the bias-variance tradeoff, what does 'bias' refer to?",
        "Variance refers to:": "In machine learning models, what does 'variance' specifically refer to?",
        "Regularization helps:": "What is the primary benefit of applying regularization to a machine learning model?",
        "L1 is called:": "L1 Regularization is also commonly known as by what name?",
        "Clustering is:": "Sorting data points into distinct, unlabeled groups is known as clustering. What kind of learning is this?",
        "ROC curve plots:": "An ROC curve is used to evaluate models by plotting which two metrics against each other?",
        "Feature scaling needed for:": "Which of these algorithms typically requires feature scaling (like normalization) to function correctly?",
        "Cross-validation is for:": "What is the primary purpose of using cross-validation techniques?",
        "Logistic output is:": "What type of mathematical output is generated by a logistic regression function?",
        "Imbalanced metric:": "When dealing with a highly imbalanced dataset, which evaluation metric is usually the best choice?",

        # Operating Systems
        "OS is:": "Which of the following best describes the primary function of an Operating System?",
        "Process is:": "In an operating system, how is a 'process' formally defined?",
        "PCB stands for:": "In OS process management, what does the acronym PCB stand for?",
        "CPU scheduling decides:": "What is the main purpose of a CPU scheduling algorithm?",
        "FCFS means:": "What does the CPU scheduling acronym FCFS stand for?",
        "Round Robin uses:": "Which of the following is a key characteristic used by the Round Robin scheduling algorithm?",
        "Deadlock is:": "In modern operating systems, what is a 'deadlock'?",
        "Semaphore used for:": "What is the primary purpose of a semaphore in concurrent programming?",
        "Paging avoids:": "What common memory management problem is paging designed to avoid?",
        "Thrashing is:": "What does the term 'thrashing' refer to regarding computer memory?",
        "Virtual memory uses:": "Virtual memory allows an OS to use a portion of what hardware component as additional RAM?",
        "Preemptive:": "Which of the following scheduling algorithms is strictly preemptive?",
        "Critical section deals with:": "A 'critical section' in code primarily deals with the management of what?",
        "Starvation:": "In process scheduling, what defines 'starvation'?",
        "Banker algo avoids:": "What specific problem does the Banker's Algorithm attempt to prevent?",
        "Context switch:": "What actually happens during a 'context switch'?",
        "Kernel is:": "How is the 'kernel' defined in the context of an operating system?",
        "Multithreading improves:": "What is a primary benefit of using multithreading in an application?",
        "Internal frag in:": "Which memory management scheme is most prone to internal fragmentation?",
        "External frag in:": "Which memory management scheme is most prone to external fragmentation?",
        "Mutual exclusion:": "What does 'mutual exclusion' guarantee in concurrent programming?",
        "I/O bound:": "If a process spends more time doing I/O than doing computation, it is classified as:",
        "CPU bound:": "If a process spends more time executing computations than waiting on I/O, it is classified as:",
        "FIFO is:": "First-In-First-Out (FIFO) can refer to memory management or:",
        "Dispatcher does:": "What is the core responsibility of the OS dispatcher?",

        # DBMS
        "DBMS stands for:": "What does the acronym DBMS stand for?",
        "SQL is:": "Which of the following best describes what SQL is?",
        "Primary key:": "What is the primary characteristic of a Primary Key in a relational table?",
        "Foreign key:": "What is the primary purpose of a Foreign Key constraint?",
        "Normalization reduces:": "What is the primary goal of applying database normalization?",
        "1NF removes:": "To achieve First Normal Form (1NF), what must be removed from a database table?",
        "2NF removes:": "To achieve Second Normal Form (2NF), a table must already be in 1NF and have removed what else?",
        "3NF removes:": "To achieve Third Normal Form (3NF), a table must already be in 2NF and have removed what else?",
        "Join is used for:": "What is the primary function of a SQL JOIN operation?",
        "Index improves:": "What is the primary benefit of creating an index on a database table?",
        "ACID stands for:": "In database transaction systems, what does the acronym ACID stand for?",
        "Transaction is:": "In database management, what formally defines a 'transaction'?",
        "Deadlock in DB:": "What characterizes a deadlock state in a database management system?",
        "ER model:": "What type of tool is the Entity-Relationship (ER) model?",
        "Entity:": "In an ER diagram, how is an 'Entity' best described?",
        "Attribute:": "In an ER diagram, what does an 'Attribute' represent?",
        "Candidate key:": "Which of the following best describes a Candidate Key?",
        "Super key:": "Which of the following best describes a Super Key?",
        "DDL includes:": "Which of the following SQL commands is classified as Data Definition Language (DDL)?",
        "DML includes:": "Which of the following SQL commands is classified as Data Manipulation Language (DML)?",
        "View is:": "In a database, what is a 'View'?",
        "Trigger is:": "What is a database 'trigger'?",
        "Stored procedure:": "What is a stored procedure in a database management system?",
        "Concurrency control:": "What is the primary goal of database concurrency control?",
        "Locking ensures:": "Using locks in transactions primarily ensures which ACID property?",

        # Software Engineering
        "SDLC is:": "What does the acronym SDLC stand for in software engineering?",
        "Waterfall is:": "Which of the following best describes the Waterfall model's approach to development?",
        "Agile is:": "Which of the following best categorizes the Agile software development methodology?",
        "Scrum uses:": "Scrum is an agile framework that organizes work into short, time-boxed periods known as what?",
        "Unit testing:": "What is the primary focus of Unit Testing in software development?",
        "Integration testing:": "What is the main goal of conducting Integration Testing?",
        "System testing:": "What does System Testing generally evaluate?",
        "Black box:": "What aspect of software does Black Box testing focus on?",
        "White box:": "White Box testing fundamentally requires the tester to have access to what?",
        "Requirement is:": "In software engineering, how is a 'requirement' fundamentally defined?",
        "Feasibility:": "A feasibility study primarily determines if a proposed software project is what?",
        "Risk mgmt:": "What is the primary goal of Risk Management in a software project?",
        "UML is:": "Unified Modeling Language (UML) is commonly used to create what?",
        "Use case:": "In software design, what does a 'use case' describe?",
        "Version control:": "What is the essential function of a Version Control System (VCS)?",
        "Git is:": "What type of software tool is Git?",
        "CI/CD:": "The practices of Continuous Integration and Continuous Deployment (CI/CD) focus on what?",
        "Bug:": "In software development, what is commonly referred to as a 'bug'?",
        "Debugging:": "What does the process of 'debugging' entail?",
        "Maintenance:": "In the SDLC, what does the 'maintenance' phase typically involve?",
        "Prototyping:": "What is the main purpose of creating a software 'prototype'?",
        "Spiral model:": "The Spiral model of software development is primarily driven by what factor?",
        "Verification:": "In quality assurance, 'Verification' aims to confirm what?",
        "Validation:": "In quality assurance, 'Validation' aims to confirm what?",
        "Deployment:": "What does 'deployment' mean concerning a software application?",

        # DAA
        "DAA is:": "Design and Analysis of Algorithms (DAA) is the study of what?",
        "Time complexity:": "What does an algorithm's 'time complexity' measure?",
        "Binary search:": "What is the typical time complexity of a Binary Search operation?",
        "Linear search:": "What is the typical time complexity of a Linear Search algorithm?",
        "Merge sort:": "What is the average time complexity of the Merge Sort algorithm?",
        "Quick sort avg:": "What is the average time complexity of the Quick Sort algorithm?",
        "Worst quick sort:": "What is the worst-case time complexity of the Quick Sort algorithm?",
        "Greedy uses:": "What is the fundamental strategy used by a Greedy Algorithm?",
        "DP uses:": "Dynamic Programming (DP) is highly effective when a problem exhibits what characteristic?",
        "Recursion is:": "In algorithmic design, how is 'recursion' defined?",
        "Stack used in:": "Which data structure is fundamentally used by the operating system to support recursion?",
        "Heap is:": "What underlying data structure is a 'heap' typically based upon?",
        "Graph is:": "A data graph is a non-linear structure composed of what basic elements?",
        "BFS uses:": "Which data structure does Breadth-First Search (BFS) inherently rely upon?",
        "DFS uses:": "Which data structure does Depth-First Search (DFS) inherently rely upon?",
        "Dijkstra finds:": "What problem does Dijkstra's Algorithm solve?",
        "Prim algo:": "Prim's Algorithm is used to discover what structure within a graph?",
        "Kruskal:": "Kruskal's Algorithm is used to discover what structure within a graph?",
        "NP complete:": "Which of the following generally describes NP-complete problems?",
        "Big O:": "In asymptotic notation, what does Big O notation represent?",
        "Big Omega:": "In asymptotic notation, what does Big Omega (Ω) notation represent?",
        "Big Theta:": "In asymptotic notation, what does Big Theta (Θ) notation represent?",
        "Divide conquer:": "Which algorithmic paradigm breaks a problem down, solves subproblems recursively, and combines the results?",
        "Backtracking:": "Which design paradigm abandons a path of execution as soon as it determines that it cannot possibly lead to a valid solution?",
        "Branch bound:": "Branch and Bound is primarily used to solve what category of problems?"
    }

    if q in mapping:
        q_dict["question"] = mapping[q]
    
    return q_dict

# Read the generated fixture
with open("quiz/fixtures/subject_questions.json", "r") as f:
    data = json.load(f)

# Update questions
for item in data:
    if "fields" in item:
        item["fields"] = improve_question(item["fields"])

# Save it back
with open("quiz/fixtures/subject_questions.json", "w") as f:
    json.dump(data, f, indent=2)

print("All questions updated successfully for better clarity.")
