# Generated by Django 4.2.30 on 2026-04-19 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_index', models.IntegerField(help_text='0=A, 1=B, 2=C, 3=D')),
                ('subject', models.CharField(choices=[('machine_learning', 'Machine Learning'), ('operating_systems', 'Operating Systems'), ('dbms', 'DBMS'), ('software_engineering', 'Software Engineering'), ('daa', 'DAA')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('subject', models.CharField(choices=[('machine_learning', 'Machine Learning'), ('operating_systems', 'Operating Systems'), ('dbms', 'DBMS'), ('software_engineering', 'Software Engineering'), ('daa', 'DAA')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.IntegerField(default=0, help_text='Time taken in seconds')),
                ('accuracy', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
